version: '3.8'
services:
  db:
    container_name: postgres
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      DB_NAME: anp-sample
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U admin']
      interval: 30s
      timeout: 10s
      retries: 20
    volumes:
      - ../scripts/postgres:/docker-entrypoint-initdb.d
  test_runner:
    container_name: test_runner
    build:
      context: '../'
      dockerfile: 'dockerfiles/ci.Dockerfile'
      network: host
      args:
        NPM_TOKEN: ${NPM_TOKEN}
    environment:
      DB_URL: postgresql://admin:password@db:5432/anp-sample?schema=public
      PORT: 4000
      CORS_ORIGIN: '[*]'
    links:
      - db
    depends_on:
      - db
